pkgs <- c("RCurl")

for (pkg in pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cran.rstudio.com")
  }
}

wrap.js.fun <- function(s)
{
  if (class(s) != "javascript_function")
    stop("Can only wrap javascript_function s");
  function(...) {
    Rserve::self.oobMessage(list(s, ...))
  }
}

wrap.r.fun <- Rserve:::ocap

give.first.functions <- function()
{
    data <- iris[, c("Sepal.Length", "Petal.Length")]
    list(
        rversion = wrap.r.fun(function() as.character(getRversion())),
        dummy_html = wrap.r.fun(function() {
          sprintf("<p>HTML generated by R %s</p>", getRversion())
        }),
        aplot = wrap.r.fun(function(clusters = 3) {
          t <- tempfile(fileext = ".png")
          png(file = t)

          km <- kmeans(data, clusters)
          plot(data[[1]], data[[2]],
            col = km$cluster,
            pch = 19,
            cex = 2,
            xlab = names(data)[1],
            ylab = names(data)[2]
          )
          points(km$centers, pch = 4, cex = 4, lwd = 4)
          dev.off()
          on.exit(unlink(t))

          txt <- RCurl::base64Encode(
            readBin(t, "raw", file.info(t)[1, "size"]),
            "txt"
          )

          return(sprintf("data:image/png;base64,%s", txt))
        })
    )
}

####################################################################################################
# make.oc turns a function into an object capability accessible from the remote side

# oc.init must return the first capability accessible to the remote side
oc.init <- function()
{
  wrap.r.fun(give.first.functions)
}
